name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist

    - run: mkdir -p ~/.ssh/keys

    - name: Prepare SSH config
      run: |
        set -xe
        cat >> ~/.ssh/keys/vps-key.pem<< EOF
        ${{ secrets.VPS_SSH_KEY }}
        EOF
        chmod 0600 ~/.ssh/keys/vps-key.pem

    - name: Scan SSH host key fingerprint
      run: ssh-keyscan -v -p ${{ secrets.VPS_SSH_PORT }} -H ${{ secrets.VPS_SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: ls
    # run: rsync -vcrptmiz -e "ssh -i ~/.ssh/keys/vps-key.pem -p ${{ secrets.VPS_SSH_PORT }}" --chown=nginx:nginx ./dist/* ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_HOST }}:/opt/convolve

      
        
      


